from .viewDirector import DirectorViewSet
from .viewTeaching import TeachingViewSet
from .viewCategory import CategoryViewSet
from .viewArea import AreaViewSet
from .viewModality import ModalityViewSet
from .viewEducationalLevel import EducationalLevelViewSet
from .viewInstitution import InstitutionViewSet
from .viewDetailInstitution import DetailInstitutionViewSet
from .viewDegree import DegreeViewSet
from .viewCourse import CourseViewSet
from .viewCompetence import CompetenceViewSet
from .viewCapacity import CapacityViewSet
from .viewCourseAssignment import CourseAssignmentViewSet
from .viewStudent import StudentViewSet
from .viewTeacherInstitutionAssignment import TeacherInstitutionAssignmentViewSet