from .DirectorFilter import DirectorFilter
from .TeachingFilter import TeachingFilter
from .CategoryFilter import CategoryFilter
from .AreaFilter import AreaFilter
from .ModalityFilter import ModalityFilter
from .EducationalLevelFilter import EducationalLevelFilter
from .InstitutionFilter import InstitucionFilter
from .DetailInstitutionFilter import DetailInstitutionFilter
from .DegreeFilter import DegreeFilter
from .CourseFilter import CourseFilter
from .CompetenceFilter import CompetenceFilter
from .CapacityFilter import CapacityFilter
from .CourseAssignmentFilter import CourseAssignmentFilter
from .StudentFilter import StudentFilter
from .TeacherInstitutionAssignment import TeacherInstitutionAssignmentFilter